import React, { useState, useEffect, useMemo } from "react";
import axios from "axios";
import { ADMIN_PATH } from "../constant";
import {
  computeDeliveryGap,
  computeCurrentCategory,
  generateAISuggestion,
  getCurrentCategoryNumber,
  getDateStringInTimeZone,
  getDeliveryGapNumber,
  getPeakFrequencyNumber,
  getTodayEffectiveStatus,
  getTodayDeliveryStatus,
  normalizeDeliveryGap,
  resolvePeakFrequency,
} from "../utils/aiSuggestionEngine";
import {
  getCachedAISuggestionCandidates,
  patchCachedUserInfoCustomer,
} from "../utils/customerInfoClientCache";
import { exportToExcel } from "../utils/excelExport";
import AISuggestionTable from "../components/AISuggestionTable";

const normalizePotential = (value) => {
  const raw = String(value ?? "")
    .trim()
    .toUpperCase();

  if (!raw) return "T1";

  const normalized = raw.replace(/T\s*(\d+)/, "T$1");
  const match = normalized.match(/^T(\d+)$/);
  if (match) {
    const num = Number(match[1]);
    return Number.isFinite(num) && num > 0 ? `T${num}` : "T1";
  }

  return "T1";
};

const getPotentialNumber = (value) => {
  const potential = normalizePotential(value);
  const n = Number(potential.slice(1));
  return Number.isFinite(n) && n > 0 ? n : 1;
};

const getCustomerDeliveryGapNumber = (customer) => {
  const todayDate = getDateStringInTimeZone(new Date(), "Asia/Kolkata");
  const rawDeliveryGap = computeDeliveryGap(customer?.last8Days, todayDate);
  const deliveryGap = normalizeDeliveryGap(customer?.deliveryGap || rawDeliveryGap);
  return getDeliveryGapNumber(deliveryGap);
};

const compareByName = (a, b) =>
  (a.customer.name || "").localeCompare(b.customer.name || "");

const AISuggestions = () => {
  const [customers, setCustomers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const [searchQuery] = useState("");
  const [filterOption, setFilterOption] = useState("ALL");


  const [sortOption, setSortOption] = useState("DELIVERY_GAP");
  const [logicOption, setLogicOption] = useState("logic1");

  const [currentPage, setCurrentPage] = useState(1);
  const [updatingSuggestionId, setUpdatingSuggestionId] = useState(null);
  const PAGE_SIZE = 25;

  useEffect(() => {
    setCurrentPage(1);
  }, [filterOption, sortOption]);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      // Fetch only D1-D3 candidates through a short-lived client/backend cache.
      const userInfoData = await getCachedAISuggestionCandidates();
      let allCustomers = [];

      // Backend returns an array if no pagination is requested, or { customers: [...] } 
      if (Array.isArray(userInfoData)) {
        allCustomers = userInfoData;
      } else if (userInfoData && Array.isArray(userInfoData.customers)) {
        allCustomers = userInfoData.customers;
      }

      // 1. Filter out customers with missing todayOverride and non-D1-D3 customers.
      // 2. Filter to show only PENDING status for today (exclude Delivered/Checked)
      const validCustomers = allCustomers.filter((c) => {
        if (!c || !c.todayOverride) return false;
        const currentCategoryNumber = getCurrentCategoryNumber(
          computeCurrentCategory(c.last8Days),
        );
        if (currentCategoryNumber < 1 || currentCategoryNumber > 3) return false;

        // ⭐ OPTIMIZATION: Filter only PENDING customers (no additional reads)
        const todayStatus = getTodayDeliveryStatus(c);
        return todayStatus === "pending";
      });

      // 2. Store valid customers (Suggestions are dynamically generated by useMemo)
      setCustomers(validCustomers);
    } catch (err) {
      console.error("Error fetching customers for AI suggestions:", err);
      setError("Failed to load AI suggestions. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const processedData = useMemo(() => {
    const data = customers.map((customer) => {
      return {
        customer,
        suggestion: generateAISuggestion(customer, logicOption),
      };
    });

    data.sort((a, b) => {
      if (b.suggestion.confidence !== a.suggestion.confidence) {
        return b.suggestion.confidence - a.suggestion.confidence;
      }
      return (a.customer.name || "").localeCompare(b.customer.name || "");
    });

    return data;
  }, [customers, logicOption]);

  const filteredData = useMemo(() => {
    return processedData.filter((item) => {
      // Search (left intact; dropdown selection now controls customer type)
      const searchLower = searchQuery.toLowerCase();
      const matchesSearch =
        !searchQuery ||
        (item.customer.name && item.customer.name.toLowerCase().includes(searchLower)) ||
        (item.customer.custid && item.customer.custid.toLowerCase().includes(searchLower)) ||
        (item.customer.business && item.customer.business.toLowerCase().includes(searchLower));

      // Customer-type dropdown filter
      // AI candidates from backend (`/ai-suggestions/candidates`) may not always include businessType.
      // Try multiple fields used across the app: businessType, business, and zone.businessType (if present).
      const customerBusinessType = String(item.customer?.businessType || "").trim();
      const customerBusiness = String(item.customer?.business || "").trim();
      const customerFromZone = String(item.customer?.zone?.businessType || "").trim();

      const normalizedCustomerType = customerBusinessType || customerBusiness || customerFromZone;

      // Strict match (case-sensitive values in dropdown). Normalize both to be safe.
      const matchesCustomerType =
        filterOption === "ALL" ||
        String(normalizedCustomerType).trim().toLowerCase() ===
          String(filterOption).trim().toLowerCase();


      return matchesSearch && matchesCustomerType;
    });
  }, [processedData, searchQuery, filterOption]);

  const sortedData = useMemo(() => {
    const dataToSort = [...filteredData];
    
    switch (sortOption) {
      case "NAME_ASC":
        return dataToSort.sort((a, b) => (a.customer.name || "").localeCompare(b.customer.name || ""));
      case "NAME_DESC":
        return dataToSort.sort((a, b) => (b.customer.name || "").localeCompare(a.customer.name || ""));
      case "TOGGLE_ON_FIRST":
        return dataToSort.sort((a, b) => {
          const aOn = getTodayEffectiveStatus(a.customer) === "ON" ? 1 : 0;
          const bOn = getTodayEffectiveStatus(b.customer) === "ON" ? 1 : 0;
          return bOn - aOn;
        });
      case "TOGGLE_OFF_FIRST":
        return dataToSort.sort((a, b) => {
          const aOn = getTodayEffectiveStatus(a.customer) === "ON" ? 1 : 0;
          const bOn = getTodayEffectiveStatus(b.customer) === "ON" ? 1 : 0;
          return aOn - bOn;
        });
      case "PEAK_FREQUENCY":
        return dataToSort.sort((a, b) => {
          const diff =
            getPeakFrequencyNumber(resolvePeakFrequency(b.customer)) -
            getPeakFrequencyNumber(resolvePeakFrequency(a.customer));
          return diff || compareByName(a, b);
        });
      case "PEAK_POTENTIAL":
        return dataToSort.sort((a, b) => {
          const diff =
            getPotentialNumber(b.customer.potential) -
            getPotentialNumber(a.customer.potential);
          return diff || compareByName(a, b);
        });
      case "DELIVERY_GAP":
        return dataToSort.sort((a, b) => {
          const diff =
            getCustomerDeliveryGapNumber(a.customer) -
            getCustomerDeliveryGapNumber(b.customer);
          return diff || compareByName(a, b);
        });
      case "DEFAULT":
      default:
        return dataToSort;
    }
  }, [filteredData, sortOption]);

  const totalPages = Math.max(1, Math.ceil(sortedData.length / PAGE_SIZE));
  const currentData = sortedData.slice(
    (currentPage - 1) * PAGE_SIZE,
    currentPage * PAGE_SIZE
  );

  const handleNextPage = () => {
    if (currentPage < totalPages) setCurrentPage((prev) => prev + 1);
  };

  const handlePrevPage = () => {
    if (currentPage > 1) setCurrentPage((prev) => prev - 1);
  };

  const handleApplySuggestion = async (customer, nextStatus) => {
    if (!customer?.id || updatingSuggestionId === customer.id) return;

    const previousOverride = customer.todayOverride;
    const optimisticOverride = { ...previousOverride, status: nextStatus };

    setCustomers((prev) =>
      prev.map((row) =>
        row.id === customer.id ? { ...row, todayOverride: optimisticOverride } : row
      )
    );

    try {
      setUpdatingSuggestionId(customer.id);
      const res = await axios.post(`${ADMIN_PATH}/customer/toggle-delivery`, {
        id: customer.id,
        status: nextStatus,
      });
      const saved = res?.data?.todayOverride;
      if (saved?.date && saved?.status) {
        patchCachedUserInfoCustomer(customer.id, (row) => ({
          ...row,
          todayOverride: saved,
        }));
        setCustomers((prev) =>
          prev.map((row) =>
            row.id === customer.id ? { ...row, todayOverride: saved } : row
          )
        );
      }
    } catch (err) {
      console.error("AI suggestion apply error:", err);
      setCustomers((prev) =>
        prev.map((row) =>
          row.id === customer.id ? { ...row, todayOverride: previousOverride } : row
        )
      );
    } finally {
      setUpdatingSuggestionId(null);
    }
  };

  const handleDownloadExcel = () => {
    exportToExcel(sortedData, logicOption);
  };

  return (
    <div className="p-4 bg-gray-100 min-h-screen">
      <div className="flex justify-between items-center mb-4 gap-4">
        <h1 className="text-xl font-bold whitespace-nowrap">AI Suggestions</h1>
        <div className="flex gap-2">
          <select
            value={filterOption}
            onChange={(e) => setFilterOption(e.target.value)}
            className="border border-gray-300 px-2 py-1 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
          >
            <option value="ALL">All Customer Types</option>
            <option value="Kirana Store">Kirana Store</option>
            <option value="Hotel">Hotel</option>
            <option value="Meat Shop">Meat Shop</option>
            <option value="Restuarant & Cafe">Restuarant & Cafe</option>
            <option value="Canteen & Catering">Canteen & Catering</option>
            <option value="Vegetables Shop">Vegetables Shop</option>
            <option value="Condiments">Condiments</option>
            <option value="Bakery & Cake Shop">Bakery & Cake Shop</option>
            <option value="Hostel & PG">Hostel & PG</option>
            <option value="Street Food Cart">Street Food Cart</option>
            <option value="Wholesaler">Wholesaler</option>
            <option value="Supermart">Supermart</option>
          </select>
          <select
            value={sortOption}
            onChange={(e) => setSortOption(e.target.value)}
            className="border border-gray-300 px-2 py-1 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
          >
            <option value="DEFAULT">Sort: Default (AI Confidence)</option>
            <option value="NAME_ASC">Name (A-Z)</option>
            <option value="NAME_DESC">Name (Z-A)</option>
            <option value="TOGGLE_ON_FIRST">Toggle (ON First)</option>
            <option value="TOGGLE_OFF_FIRST">Toggle (OFF First)</option>
            <option value="PEAK_FREQUENCY">Peak Frequency</option>
            <option value="PEAK_POTENTIAL">Peak Potential</option>
            <option value="DELIVERY_GAP">Delivery Gap (G0 First)</option>
          </select>
          <select
            value={logicOption}
            onChange={(e) => setLogicOption(e.target.value)}
            className="border border-gray-300 px-2 py-1 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
          >
            <option value="logic1">Logic 1</option>
            <option value="logic2">Logic 2</option>
            <option value="logic3">Logic 3</option>
            <option value="logic4">Logic 4</option>
            <option value="logic5">Logic 5</option>
            <option value="logic6">Logic 6</option>
          </select>
          <select
            value={filterOption}
            onChange={(e) => setFilterOption(e.target.value)}
            className="border border-gray-300 px-2 py-1 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
          >
            <option value="ALL">All Suggestions</option>
            <option value="TURN_ON_TOMORROW">Turn ON Tomorrow</option>
            <option value="TURN_OFF_TOMORROW">Turn OFF Tomorrow</option>
          </select>
          <button
            onClick={handleDownloadExcel}
            disabled={loading || sortedData.length === 0}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white font-semibold px-4 py-1 rounded-lg text-sm transition duration-200 whitespace-nowrap"
          >
            Download Excel
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-50 text-red-600 p-4 rounded-md mb-6 border border-red-200">
          {error}
        </div>
      )}

      <AISuggestionTable
        data={currentData}
        loading={loading}
        onApplySuggestion={handleApplySuggestion}
        updatingSuggestionId={updatingSuggestionId}
      />

      {!loading && !error && (
        <div className="mt-4 flex items-center justify-between">
          <button
            type="button"
            onClick={handlePrevPage}
            disabled={currentPage === 1}
            className="bg-gray-200 text-gray-800 px-4 py-2 rounded disabled:opacity-50"
          >
            Previous
          </button>
          
          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-700">
              Page {currentPage} of {totalPages}
            </span>
          </div>

          <button
            type="button"
            onClick={handleNextPage}
            disabled={currentPage === totalPages}
            className="bg-blue-600 text-white px-4 py-2 rounded disabled:opacity-50"
          >
            Next
          </button>
        </div>
      )}
    </div>
  );
};

export default AISuggestions;
