import React, { useState, useEffect, useMemo } from "react";
import axios from "axios";
import { ADMIN_PATH } from "../constant";
import {
  computeDeliveryGap,
  computeCurrentCategory,
  generateAISuggestion,
  getCurrentCategoryNumber,
  getDateStringInTimeZone,
  getDeliveryGapNumber,
  getPeakFrequencyNumber,
  getTodayEffectiveStatus,
  getTodayDeliveryStatus,
  normalizeDeliveryGap,
  resolvePeakFrequency,
} from "../utils/aiSuggestionEngine";
import {
  getCachedAISuggestionCandidates,
  patchCachedUserInfoCustomer,
} from "../utils/customerInfoClientCache";
import { exportToExcel } from "../utils/excelExport";
import DummyAISuggestionTable from "../components/DummyAISuggestionTable";

const normalizePotential = (value) => {
  const raw = String(value ?? "")
    .trim()
    .toUpperCase();

  if (!raw) return "T1";

  const normalized = raw.replace(/T\s*(\d+)/, "T$1");
  const match = normalized.match(/^T(\d+)$/);
  if (match) {
    const num = Number(match[1]);
    return Number.isFinite(num) && num > 0 ? `T${num}` : "T1";
  }

  return "T1";
};

const getPotentialNumber = (value) => {
  const potential = normalizePotential(value);
  const n = Number(potential.slice(1));
  return Number.isFinite(n) && n > 0 ? n : 1;
};

const getCustomerDeliveryGapNumber = (customer) => {
  const todayDate = getDateStringInTimeZone(new Date(), "Asia/Kolkata");
  const rawDeliveryGap = computeDeliveryGap(customer?.last8Days, todayDate);
  const deliveryGap = normalizeDeliveryGap(customer?.deliveryGap || rawDeliveryGap);
  return getDeliveryGapNumber(deliveryGap);
};

const compareByName = (a, b) =>
  (a.customer.name || "").localeCompare(b.customer.name || "");

const DummyAISuggestions = () => {
  const [customers, setCustomers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const [searchQuery] = useState("");
  const [businessTypeFilter, setBusinessTypeFilter] = useState("ALL");
  const [businessTypes, setBusinessTypes] = useState([]);
  const [suggestionFilterOption, setSuggestionFilterOption] = useState("ALL");


  // Default sorting: TOGGLE (ON FIRST) as soon as page opens
  const [sortOption, setSortOption] = useState("TOGGLE_ON_FIRST");

  // INDIVIDUAL LOGIC MAPPING: { customerId: 'logic1' }
  const [rowLogics, setRowLogics] = useState({});

  const handleLogicChange = (customerId, newLogic) => {
    setRowLogics((prev) => ({
      ...prev,
      [customerId]: newLogic
    }));
  };

  const [currentPage, setCurrentPage] = useState(1);
  const [updatingSuggestionId, setUpdatingSuggestionId] = useState(null);
  const PAGE_SIZE = 25;

  useEffect(() => {
    setCurrentPage(1);
  }, [businessTypeFilter, suggestionFilterOption, sortOption]);

  useEffect(() => {
    fetchData();
  }, []);


  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      // Fetch only D1-D3 candidates through a short-lived client/backend cache.
      const userInfoData = await getCachedAISuggestionCandidates();
      
      // Fetch business types dynamically
      try {
        const btRes = await axios.get(`${ADMIN_PATH}/business-types`);
        setBusinessTypes(btRes.data || []);
      } catch (err) {
        console.error("Error fetching business types:", err);
      }

      let allCustomers = [];

      // Backend returns an array if no pagination is requested, or { customers: [...] } 
      if (Array.isArray(userInfoData)) {
        allCustomers = userInfoData;
      } else if (userInfoData && Array.isArray(userInfoData.customers)) {
        allCustomers = userInfoData.customers;
      }

      // 1. Filter out customers with missing todayOverride and non-D1-D3 customers.
      // 2. Filter to show only PENDING status for today (exclude Delivered/Checked)
      const validCustomers = allCustomers.filter((c) => {
        if (!c || !c.todayOverride) return false;
        const currentCategoryNumber = getCurrentCategoryNumber(
          computeCurrentCategory(c.last8Days),
        );
        if (currentCategoryNumber < 1 || currentCategoryNumber > 3) return false;

        // ⭐ OPTIMIZATION: Filter only PENDING customers (no additional reads)
        const todayStatus = getTodayDeliveryStatus(c);
        return todayStatus === "pending";
      });

      // 2. Store valid customers (Suggestions are dynamically generated by useMemo)
      setCustomers(validCustomers);
    } catch (err) {
      console.error("Error fetching customers for AI suggestions:", err);
      setError("Failed to load AI suggestions. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const processedData = useMemo(() => {
    const data = customers.map((customer) => {
      const customerLogic = rowLogics[customer.id] || "logic1";
      return {
        customer,
        suggestion: generateAISuggestion(customer, customerLogic),
      };
    });

    data.sort((a, b) => {
      if (b.suggestion.confidence !== a.suggestion.confidence) {
        return b.suggestion.confidence - a.suggestion.confidence;
      }
      return (a.customer.name || "").localeCompare(b.customer.name || "");
    });

    return data;
  }, [customers, rowLogics]);

  const filteredData = useMemo(() => {
    return processedData.filter((item) => {
      // Search (left intact; dropdown selection now controls customer type)
      const searchLower = searchQuery.toLowerCase();
      const matchesSearch =
        !searchQuery ||
        (item.customer.name && item.customer.name.toLowerCase().includes(searchLower)) ||
        (item.customer.custid && item.customer.custid.toLowerCase().includes(searchLower)) ||
        (item.customer.business && item.customer.business.toLowerCase().includes(searchLower));

      // Suggestion dropdown filter (Turn ON/OFF Tomorrow)
      const suggestion = item?.suggestion?.suggestion;
      const filterOption = suggestionFilterOption;
      const isTurnOnTomorrow = filterOption === "TURN_ON_TOMORROW";
      const isTurnOffTomorrow = filterOption === "TURN_OFF_TOMORROW";

      // Suggestion dropdown should match against the generated suggestion.
      const matchesSuggestionOption =
        filterOption === "ALL" ||
        (isTurnOnTomorrow && suggestion === "TURN_ON_TOMORROW") ||
        (isTurnOffTomorrow && suggestion === "TURN_OFF_TOMORROW");

      // If user selected a Turn ON/OFF option and the row does not match, drop it.

      if (!matchesSuggestionOption) return false;

      // Customer-type dropdown filter (Kirana/Hotel/etc)
      // AI candidates from backend (`/ai-suggestions/candidates`) may not always include businessType.
      // Try multiple fields used across the app: businessType, business, and zone.businessType (if present).
      const customerBusinessType = String(item.customer?.businessType || "").trim();
      const customerBusiness = String(item.customer?.business || "").trim();
      const customerFromZone = String(item.customer?.zone?.businessType || "").trim();
      const normalizedCustomerType = customerBusinessType || customerBusiness || customerFromZone;

      // Strict match (normalize to be safe)
      const matchesCustomerType =
        businessTypeFilter === "ALL" ||
        String(normalizedCustomerType).trim().toLowerCase() ===
          String(businessTypeFilter).trim().toLowerCase();

      return matchesSearch && matchesCustomerType;
    });
  }, [processedData, searchQuery, businessTypeFilter, suggestionFilterOption]);


  const sortedData = useMemo(() => {
    const dataToSort = [...filteredData];

    switch (sortOption) {
      case "NAME_ASC":
        return dataToSort.sort((a, b) => (a.customer.name || "").localeCompare(b.customer.name || ""));
      case "NAME_DESC":
        return dataToSort.sort((a, b) => (b.customer.name || "").localeCompare(a.customer.name || ""));
      case "TOGGLE_ON_FIRST":
        return dataToSort.sort((a, b) => {
          const aOn = getTodayEffectiveStatus(a.customer) === "ON" ? 1 : 0;
          const bOn = getTodayEffectiveStatus(b.customer) === "ON" ? 1 : 0;
          return bOn - aOn;
        });
      case "TOGGLE_OFF_FIRST":
        return dataToSort.sort((a, b) => {
          const aOn = getTodayEffectiveStatus(a.customer) === "ON" ? 1 : 0;
          const bOn = getTodayEffectiveStatus(b.customer) === "ON" ? 1 : 0;
          return aOn - bOn;
        });
      case "PEAK_FREQUENCY":
        return dataToSort.sort((a, b) => {
          const diff =
            getPeakFrequencyNumber(resolvePeakFrequency(b.customer)) -
            getPeakFrequencyNumber(resolvePeakFrequency(a.customer));
          return diff || compareByName(a, b);
        });
      case "PEAK_POTENTIAL":
        return dataToSort.sort((a, b) => {
          const diff =
            getPotentialNumber(b.customer.potential) -
            getPotentialNumber(a.customer.potential);
          return diff || compareByName(a, b);
        });
      case "DELIVERY_GAP":
        return dataToSort.sort((a, b) => {
          const diff =
            getCustomerDeliveryGapNumber(a.customer) -
            getCustomerDeliveryGapNumber(b.customer);
          return diff || compareByName(a, b);
        });
      case "DEFAULT":
      default:
        return dataToSort;
    }
  }, [filteredData, sortOption]);

  const totalPages = Math.max(1, Math.ceil(sortedData.length / PAGE_SIZE));
  const currentData = sortedData.slice(
    (currentPage - 1) * PAGE_SIZE,
    currentPage * PAGE_SIZE
  );

  const handleNextPage = () => {
    if (currentPage < totalPages) setCurrentPage((prev) => prev + 1);
  };

  const handlePrevPage = () => {
    if (currentPage > 1) setCurrentPage((prev) => prev - 1);
  };

  const handleApplySuggestion = async (customer, nextStatus) => {
    if (!customer?.id || updatingSuggestionId === customer.id) return;

    const previousOverride = customer.todayOverride;
    const optimisticOverride = { ...previousOverride, status: nextStatus };

    setCustomers((prev) =>
      prev.map((row) =>
        row.id === customer.id ? { ...row, todayOverride: optimisticOverride } : row
      )
    );

    try {
      setUpdatingSuggestionId(customer.id);
      const res = await axios.post(`${ADMIN_PATH}/customer/toggle-delivery`, {
        id: customer.id,
        status: nextStatus,
      });
      const saved = res?.data?.todayOverride;
      if (saved?.date && saved?.status) {
        patchCachedUserInfoCustomer(customer.id, (row) => ({
          ...row,
          todayOverride: saved,
        }));
        setCustomers((prev) =>
          prev.map((row) =>
            row.id === customer.id ? { ...row, todayOverride: saved } : row
          )
        );
      }
    } catch (err) {
      console.error("AI suggestion apply error:", err);
      setCustomers((prev) =>
        prev.map((row) =>
          row.id === customer.id ? { ...row, todayOverride: previousOverride } : row
        )
      );
    } finally {
      setUpdatingSuggestionId(null);
    }
  };

  const handleDownloadExcel = () => {
    exportToExcel(sortedData, "Multiple Logics (Dummy)");
  };

  const totalCustomers = processedData.length;
  const suggestOnCount = processedData.filter((item) => {
    const sugg = item.suggestion?.suggestion || "";
    return sugg.includes("ON");
  }).length;
  const suggestOffCount = totalCustomers - suggestOnCount;

  const suggestOnPercentage = totalCustomers > 0 ? ((suggestOnCount / totalCustomers) * 100).toFixed(1) : 0;
  const suggestOffPercentage = totalCustomers > 0 ? ((suggestOffCount / totalCustomers) * 100).toFixed(1) : 0;

  return (
    <div className="p-6 bg-[#FAFAFA] min-h-screen font-sans">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">AI Suggestions</h1>
          <p className="text-sm text-gray-500 mt-1 font-medium">Final daily decision: Turn ON or OFF for today</p>
        </div>
        <div className="flex items-center gap-2">
          <select
            value={businessTypeFilter}
            onChange={(e) => setBusinessTypeFilter(e.target.value)}
            className="border border-gray-300 px-3 py-1.5 rounded-lg text-sm text-gray-700 font-medium focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white shadow-sm"
          >
            <option value="ALL">All Customer Types</option>
            {businessTypes.map((bt) => (
              <option key={bt} value={bt}>
                {bt}
              </option>
            ))}
          </select>
          
          <select
            value={sortOption}
            onChange={(e) => setSortOption(e.target.value)}
            className="border border-gray-300 px-3 py-1.5 rounded-lg text-sm text-gray-700 font-medium focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white shadow-sm"
          >
            <option value="DEFAULT">Sort: Default (AI Confidence)</option>
            <option value="NAME_ASC">Name (A-Z)</option>
            <option value="NAME_DESC">Name (Z-A)</option>
            <option value="TOGGLE_ON_FIRST">Toggle (ON First)</option>
            <option value="TOGGLE_OFF_FIRST">Toggle (OFF First)</option>
            <option value="PEAK_FREQUENCY">Peak Frequency</option>
            <option value="PEAK_POTENTIAL">Peak Potential</option>
            <option value="DELIVERY_GAP">Delivery Gap (G0 First)</option>
          </select>
          
          <select
            value={suggestionFilterOption}
            onChange={(e) => setSuggestionFilterOption(e.target.value)}
            className="border border-gray-300 px-3 py-1.5 rounded-lg text-sm text-gray-700 font-medium focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white shadow-sm"
          >
            <option value="ALL">All Suggestions</option>
            <option value="TURN_ON_TOMORROW">Turn ON Tomorrow</option>
            <option value="TURN_OFF_TOMORROW">Turn OFF Tomorrow</option>
          </select>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {/* Card 1 */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-green-50 flex items-center justify-center text-green-600 border border-green-100">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div className="flex flex-col">
            <span className="text-[13px] font-bold text-gray-800">Total Customers</span>
            <div className="text-3xl font-extrabold text-gray-900 mt-1">{totalCustomers}</div>
          </div>
        </div>

        {/* Card 2 */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-green-50 flex items-center justify-center text-green-600 border border-green-100">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09l2.846.813-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
            </svg>
          </div>
          <div className="flex flex-col">
            <span className="text-[13px] font-bold text-gray-800">AI Suggest ON</span>
            <div className="flex items-center gap-2 mt-1">
              <span className="text-3xl font-extrabold text-gray-900">{suggestOnCount}</span>
              <span className="px-1.5 py-0.5 rounded text-xs font-bold bg-green-100 text-green-700">{suggestOnPercentage}%</span>
            </div>
          </div>
        </div>

        {/* Card 3 */}
        <div className="bg-white rounded-xl shadow-sm border border-red-100 p-5 flex items-center gap-4 bg-gradient-to-r from-red-50/30 to-white">
          <div className="w-12 h-12 rounded-full bg-red-50 flex items-center justify-center text-red-600 border border-red-100">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div className="flex flex-col">
            <span className="text-[13px] font-bold text-gray-800">AI Suggest OFF</span>
            <div className="flex items-center gap-2 mt-1">
              <span className="text-3xl font-extrabold text-gray-900">{suggestOffCount}</span>
              <span className="px-1.5 py-0.5 rounded text-xs font-bold bg-red-100 text-red-700">{suggestOffPercentage}%</span>
            </div>
          </div>
        </div>
      </div>


      {error && (
        <div className="bg-red-50 text-red-600 p-4 rounded-md mb-6 border border-red-200">
          {error}
        </div>
      )}

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="flex justify-between items-center p-4 border-b border-gray-100">
          <span className="text-[13px] text-gray-500 font-semibold">
          </span>
          <div className="flex items-center gap-3">
          </div>
        </div>

        <DummyAISuggestionTable
          data={currentData}
          loading={loading}
          onApplySuggestion={handleApplySuggestion}
          updatingSuggestionId={updatingSuggestionId}
          rowLogics={rowLogics}
          onLogicChange={handleLogicChange}
        />
      </div>

      {!loading && !error && (
        <div className="mt-4 flex items-center justify-between">
          <button
            type="button"
            onClick={handlePrevPage}
            disabled={currentPage === 1}
            className="bg-gray-200 text-gray-800 px-4 py-2 rounded disabled:opacity-50"
          >
            Previous
          </button>

          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-700">
              Page {currentPage} of {totalPages}
            </span>
          </div>

          <button
            type="button"
            onClick={handleNextPage}
            disabled={currentPage === totalPages}
            className="bg-blue-600 text-white px-4 py-2 rounded disabled:opacity-50"
          >
            Next
          </button>
        </div>
      )}
    </div>
  );
};

export default DummyAISuggestions;
